### ISSUE TITLE
Args in stack traces can be disabled

### ISSUE THREAD

**Issue by PeeHaa** [amphp/parallel#109]
As of [PHP 7.4 args in stack traces can be disabled](https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.ini) breaking the `flattenThrowableBacktrace` function:

https://github.com/amphp/parallel/blob/master/lib/Sync/functions.php#L16

**Comment by trowski** [comment]
Committed a fix (accidentally) as part of 7f00b8effb4fb439176aba0fa392abd120cbd952.

**Comment by enumag** [comment]
Just ran into this as well. Please make a new release with this fix.

**Comment by enumag** [comment]
@trowski @kelunik Can you please make a release with this? I'm running into it over and over.

**Comment by trowski** [comment]
Tagged in `v1.4.0`.
