### ISSUE TITLE
How to run multiple processes in parallel?

### ISSUE THREAD

**Issue by JanMikes** [amphp/parallel#111]
Hi!

At first, thank you and sorry for opening issue with question.

I have been reading examples and trying for 10+ hours but still i am unable to get running multiple processes in parallel and after trying many things i am really confused without working code, i am sure you can understand how frustrated i am :-).

This example https://github.com/amphp/parallel/blob/master/examples/worker-pool.php is pretty close to what i want to achieve. Just instead of`CallableTask` use `Process::run(['bin/console', 'some-command']);`.

I want to run multiple different symfony/console commands in background as child processes and when all are finished, use their results.

I tried passing it into `Promise\all()`, yielding everything around and many things 😄 

Do you please have any tips?

**Comment by iNilo** [comment]
Looking for a working example too :( 

I need to launch 20 concurrent processes, wait for all of them to come in.

**Comment by kelunik** [comment]
If you're trying to run processes instead of tasks, I suggest to use [`amphp/process`](https://github.com/amphp/process) directly instead of using `amphp/parallel`.

You can find an [example for running multiple processes in parallel](https://github.com/amphp/process/blob/a9823125177bf8247af7cde28c24e511bc4260c0/examples/ping-many.php) in `amphp/process`.

**Comment by JanMikes** [comment]
@kelunik thank you very much! Shame on me, i was not looking for examples in that repo 🙄 😄

**Comment by JanMikes** [comment]
@kelunik i was playing around and here are my results https://github.com/JanMikes/php-async-playground it works very well and as expected, thank you once again! 😍 

@iNilo you can check it out, maybe it will help you, as well i am reading data in parent from child sub-processes and dumping them out after all subprocesses finished.

Any feedback/improvements suggestions are very welcomed :-).

**Comment by kelunik** [comment]
@JanMikes Looks fine! I only have a minor comment: Yielding promises doesn't "run" them, it just awaits the results. The operation will run whether you yield the promise or not (unless the event loop is stopped or blocked). Yielding just provides an easy way to await the result and act upon it.

https://github.com/JanMikes/php-async-playground/blob/4381e589288b983626fc2f9f7b8b2674d015a0e7/run-multiple-processes.php#L26
