### ISSUE TITLE
[BUG/QUESTION] How does one use Laravel's facades inside a Task?

### ISSUE THREAD

**Issue by ThaDaVos** [amphp/parallel#116]
I'm currently trying to use Laravel's `Storage` facade inside my custom task as I have to download and save multiple files to disk. But I'm running into an issue as I get the error `A facade root has not been set`

Are there any know solutions for this?

**Comment by kelunik** [comment]
You'll have to configure anything in the worker again, because objects are serialized and sent to another process.

**Comment by ThaDaVos** [comment]
Any guide on how? I couldn't find any guides from Laravel on how to manually configure everything again

**Comment by trowski** [comment]
How do you bootstrap your initial script? Do you include certain files?

**Comment by ThaDaVos** [comment]
I don't really know, it's a Laravel project and it bootstraps a lot - but I don't know exactly what

**Comment by DakingRT** [comment]
Any solution? I have the same problem

**Comment by kelunik** [comment]
We're both not using Laravel, so this has to be answered by somebody from the Laravel community.
