### ISSUE TITLE
Uncaught Amp\Parallel\Sync\ChannelException: The channel closed unexpectedly. Did the context die?

### ISSUE THREAD

**Issue by BasicPro** [amphp/parallel#118]
Hello!

I'm having this issue under specific conditions, not sure what I'm doing wrong. This happens when I try to call a class static method from a the callable function. But only when the class is defined in a different file than the callable function. I'm thinking it should be a problem on how composer is loading my classes but I don't understand why this happens, the classes are loaded correctly. Some help would be appreciated.

This is the error dump:

```
2020/06/12 11:27:29 [error] 28487#28487: *4176520 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Amp\Parallel\Sync\ChannelException: The channel closed unexpectedly. Did the context die? in /home/site/wp-content/plugins/test/vendor/amphp/parallel/lib/Sync/ChannelledStream.php:74
Stack trace:
#0 [internal function]: Amp\Parallel\Sync\ChannelledStream->Amp\Parallel\Sync\{closure}()
#1 /home/site/wp-content/plugins/test/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send(NULL)
#2 /home/site/wp-content/plugins/test/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)
#3 /home/site/wp-content/plugins/test/vendor/amphp/amp/lib/Deferred.php(52): class@anonymous->resolve(NULL)
#4 /home/site/wp-content/plugins/test/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve(NULL)
#5 /home/site/wp-content/plugins/test/vendor/amphp/amp/lib/Loop/NativeDriver.php(201): Amp\ByteStream" while reading response header from upstream, client: 84.122.211.44, server: www.site.com, request: "POST /wp-json/master/upload/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "www.site.com", referrer: "https://www.site.com/"

```
This is how I set the parallel class
```
use Amp\Parallel\Worker;
use Amp\Promise;

class MB_Parallel_Processor {

  public static function process(){

    $processes = ['recommended' => 0, 'high' => 2, 'low' => -2];
    $promises = [];
    foreach ($processes as $process => $input) {
        $promises[$process] = Worker\enqueueCallable('parallel_test', $input);
    }
    return Promise\wait(Promise\all($promises));
  }
}
```
This is my test callable:
```
function parallel_test($input){
  return Test_Static_Class::get_test();
}
```
This is my composer.json file.
```
{
    "require": {
        "amphp/amp": "^2.4",
        "marrouchi/polynomial-regression": "v0.2.1.1",
        "amphp/parallel": "^1.4"
    },
    "autoload": {
        "files": [
            "autoload-functions.php"
        ],
        "classmap": ["inc/"]
    }
}
```
The callable function is in "autoload-functions.php" and the test class is in the inc folder loaded with classmap. I also tried loading the classes using namespaces and PSR4 but no luck.

The thing is that if I move Test_Static_Class to autoload-functions.php everything works ok. Obviously this is not a solution because I need to use different classes in this script.

I'm quite new to using composer autoload so please pardon my ignorance, I'm sure I'm missing something obvious.

Thank you

**Comment by kelunik** [comment]
Did you run `composer dump-autoload` after changing the config?

**Comment by BasicPro** [comment]
Hello @kelunik, I do run composer dump-autoload every time I change my config. The classes that use Amp are loaded with composer so I wouldn't be able to get to this error if they weren't loaded. If I don't load them I get a different error (Class not found).

I've also switched to using Namespaces and loading with PSR4 but the issue is the same. I've also tried different ways of loading my function but no luck.

Any help would be appreciated.

**Comment by kelunik** [comment]
I missed that you're using FastCGI. Could you try running your script on the CLI and see whether you get the same error?

**Comment by BasicPro** [comment]
Thanks again for your reply @kelunik, I discovered where the issue was, as I thought, it was a silly mistake of mine. I realised it while trying the script on the CLI, so thanks for that.

I'm developing a WordPress Plugin so I had this typical check at the start of the file

```
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
```
Which was of course exiting the script in the worker and causing the issue.

You can close this, thanks again for your help and really sorry to bother you. I can't believe I lost so much time in something so silly.

Regards
