### ISSUE TITLE
ContextException: Starting the process failed

### ISSUE THREAD

**Issue by enumag** [amphp/parallel#119]
Lately I'm getting this error when using amphp/parallel. When I check the previous exception it is 
```
Amp\Parallel\Context\ContextException: Starting the process timed out.
```

Any idea what could be wrong here and how to fix it?

**Comment by enumag** [comment]
I tried to wrap the `yield enqueue($task);` call in a loop, catching the exception and retry on failure. With that I'm getting this:

```
User Warning: Worker in pool crashed with exception on shutdown: User Warning: Worker in pool exited unexpectedly with code -1
```

**Comment by enumag** [comment]
I tried with both uv and native driver, same result.

**Comment by enumag** [comment]
The issue disappeared when I removed xdebug. :thinking:

**Comment by trowski** [comment]
It appears that you're starting a worker from within another worker, is that the case?

How many workers total are you spawning?

**Comment by adrianpanicek** [comment]
Issue can be solved by modifying `Amp\Parallel\Context\Internal\ProcessHub::PROCESS_START_TIMEOUT`. It would be cool to have this configurable instead of hardcoded.

**Comment by enumag** [comment]
> It appears that you're starting a worker from within another worker, is that the case?

No. Worker was started from the main loop process.

> How many workers total are you spawning?

The error appeared with the first worker already.

**Comment by enumag** [comment]
> Issue can be solved by modifying `Amp\Parallel\Context\Internal\ProcessHub::PROCESS_START_TIMEOUT`. It would be cool to have this configurable instead of hardcoded.
> 
> EDIT: I'm using grumphp and it's spawning multiple xdebug instances. After increasing said constant the issue went away.

How far did you increase it? I remember trying that as well to no avail.

**Comment by adrianpanicek** [comment]
@enumag I just added zero at the end.

**Comment by enumag** [comment]
Yeah, I tried even higher to no avail. It's simply not working for me with xdebug active.

**Comment by sakuraza** [comment]
Hi,
I have this problem too.
I have no xdebug install, and i try to increase PROCESS_START_TIMEOUT with no success.
I just try to execute the code on this link https://amphp.org/parallel/
My environnement : 
centos 7
apache 2.4.6
php 7.2

the error : 

<status>500</status>
<error>Amp\Parallel\Context\ContextException</error>
<message>Starting the process failed</message>
<file>.../vendor/amphp/parallel/lib/Context/Process.php</file>
<line>202</line>


Thank for your help

**Comment by trowski** [comment]
Closing this issue, since this has been completely refactored in v2 to allow full customization of context IPC.
