### ISSUE TITLE
Worker in pool exited unexpectedly with code -1

### ISSUE THREAD

**Issue by portmanager005** [amphp/parallel#126]
i get this error: Worker in pool exited unexpectedly with code -1

but when I run it with xampp, then its works but not on my webhoster. Why?

` 
$urls = ["network.de","web.de"];
$promises = [];
foreach ($urls as $url => $value) {
        $promises[$url] = Worker\enqueueCallable('file_get_contents', $url);
    }
    
    $responses = Promise\wait(Promise\all($promises));
    
    foreach ($responses as $url => $response) {
        echo $response . "<br>";
    }
`

**Comment by trowski** [comment]
Worker pools are not supported inside web SAPIs. This library is designed for CLI usage.

Apologies that this issue was not replied to sooner. Please open a new issue if you have further questions. 👍
