### ISSUE TITLE
Count of working workers less then maximum pool size

### ISSUE THREAD

**Issue by ugozhaev** [amphp/parallel#128]
Good day. I use parallel-functions. I set the maximum pool size to 128 - the number of workers is stable at 128. I set it to 256 - I get different values for the number of working workers from launch to launch. But always less than the maximum value. What does it depend on?

**Comment by kelunik** [comment]
How do you query the number of workers?

**Comment by ugozhaev** [comment]
Workers are labeling processed documents by setting status and count of documents is the same with count of workers. I monitor for the number of labeled at the same time documents.

**Comment by kelunik** [comment]
So you're not looking at the number of processes but rather the produced output?

**Comment by ugozhaev** [comment]
Yes, but `ps -ef | grep -cw amp-process` shows the same

**Comment by trowski** [comment]
Unfortunately I have no idea what might have been going on here and cannot reproduce.

As this issue is fairly old, I'm going to close it. Please open a new issue if you need further support.
