### ISSUE TITLE
Adding task to $promises array dynamically

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [amphp/parallel#130]
What is the difference between the following 

`Promise\wait(Promise\some($promises));`

`Promise\wait(Promise\all($promises));`

`Promise\wait(Promise\any($promises));`

For me, I'm getting the same result for all of the above. What I'm trying to do is if any of the tasks finished I want to add one more into the pool. I thought `Promise\wait(Promise\any($promises));` will return immediately if any of the tasks finishes and I can add more to the `$promises` array. Is that possible?

**Comment by kelunik** [comment]
You could use Amp\Promise\first, but it's likely better to use the concurrent iterator from amphp/sync: https://github.com/amphp/sync/blob/54e689fd2cfbe9e8311db5c5de14e9f4c5142b20/examples/queue.php

**Comment by UnnikrishnanBhargavakurup** [comment]
@kelunik - when I use `Promise\wait(Promise\first($promises));` it's just returning NULL, I'm using some task id's in `$promises `  array as it indexes, I need those Id to update the status in DB.  Please see the below code

```
        $tasks = $this->load_taks_from_db($noOfTasks);
        for($i = 0; $i < self::MAX_POOL_SIZE; $i++) {
            // getting the service from the container
            $promises[$tasks[$i]->getId()] = Worker\enqueueCallable([$service, 'execute'], $tasks[$i]);
        }
        $responses = Promise\wait(Promise\first($promises));
         // when we reach here how I can add more tasks to the pool?
```

I would like to keep `MAX_POOL_SIZE` number for tasks processing at a time so whenever any of it finishes I need to add one more task again. How I can implement it?

**Comment by kelunik** [comment]
Try something like this based on the example I linked above:

```php
<?php

use Amp\Iterator;
use Amp\Sync\LocalSemaphore;
use function Amp\Promise\wait;
use function Amp\Sync\ConcurrentIterator\each;

require __DIR__ . '/../vendor/autoload.php';

wait(each(
    Iterator\fromIterable($this->load_taks_from_db($noOfTasks)),
    new LocalSemaphore(MAX_POOL_SIZE),
    static function ($task) {
        yield Worker\enqueueCallable([$service, 'execute'], $task);
    }
));
```

**Comment by UnnikrishnanBhargavakurup** [comment]
Thanks for the help,  just one question whether it always execute MAX_POOL_SIZE task's at a time? or it will wait for all the tasks to complete before adding the next task?

**Comment by kelunik** [comment]
It'll start a new task once the previous completed.

**Comment by UnnikrishnanBhargavakurup** [comment]
> It'll start a new task once the previous completed.

You mean everything in the pool or if one of them completes it will add a new one right?

**Comment by kelunik** [comment]
One of them. If you add some logging, you'll see it.

**Comment by UnnikrishnanBhargavakurup** [comment]
Thanks for the help!
