### ISSUE TITLE
Injecting services into my Task class trow The given data could not be serialized: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by medy36** [amphp/parallel#131]
Hello, 

i'm trying to prepare my tasks array before executing the promises. My task class requires some dependency $this->criteraiContext() and once i set this Symfony throw an 500.

```
            foreach($rules as $key => $rule ) {
			$class = new AsyncRuleEvaluator($rule, $this->criteriaContext);
			$tasks[$key] = $class;
		}
```

i have noticed that this happen only if i'm giving a service as an argument  to my Task Class (AsyncRuleEvaluator). 

**I'am sure this is a Symfony conception issue and not an AMP issue.**

Anyone that have faced the same situation can give me some help to handle my dependencies the way it should?

**Comment by kelunik** [comment]
Hey @medy36, all task dependencies will be serialized, which isn't what you want with services. Be sure to only send the data to your task. You can initialize the service in the worker separately if you need it.
