### ISSUE TITLE
can someone please provide an example of using the Environment object between workers in the pool

### ISSUE THREAD

**Issue by iamsyh** [amphp/parallel#133]
hi,

i'm trying to make use of the Environment object in my task implementation and can't seem to wrap my head around on how to use it in a called function after setting it in the run function. This is what I have so far:

```
namespace CommonFunctions;

use Amp\Parallel\Worker\Environment;

use Amp\Parallel\Worker\Task;

class Misc extends Magic_Parser implements Task {
    
    const TEST = '';
    
    private $function;
    
    private $args;

    public function __construct($function, $args) {
        parent::__construct();
        $this->function = $function;
        $this->args = $args;
    }
    
    public function run(Environment $environment)
    {
        $test= $environment->get(Misc::TEST);
        if ($db === null) { 
            $test = 'test'; // Unserializable object.
            $environment->set(Misc::TEST, $test);
        }
        $function = $this->function;
        return $this->$function($this->args);
    }
```

```
public function fetch($job) {
        
    print_r(self::TEST); // this prints empty, instead of the string "test" as set in the run method
    
    return TRUE;
    
}
```

How i assign the task in the master script:

`$tasks[] = new Misc('fetch', $job);`

Thank you!

**Comment by kelunik** [comment]
```php
    public function run(Environment $environment)
    {
        $test= $environment->get(Misc::TEST);
        if ($db === null) {  // <-- here you're using $db instead of $test
            $test = 'test'; // Unserializable object.
            $environment->set(Misc::TEST, $test);
        }
```

`print_r(self::TEST);` prints an empty string, because you defined it that way in `const TEST = ''`. You need to fetch the value from the `Environment`. Please also try using a non-empty string instead of an empty one.

**Comment by iamsyh** [comment]
> 
> 
> ```
>     public function run(Environment $environment)
>     {
>         $test= $environment->get(Misc::TEST);
>         if ($db === null) {  // <-- here you're using $db instead of $test
>         // ^^^^^^^^^^^^^^    
>         }
> ```
> 
> `print_r(self::TEST);` prints an empty string, because you defined it that way in `const TEST = ''`. You need to fetch the value from the `Environment`. Please also try using a non-empty string instead of an empty one.

ah okay. sorry but i thought setting it via the environment variable sets it automatically? and how would I go about doing it if that's not the case? apologies if this sounds like a stupid question

**Comment by kelunik** [comment]
The `Environment` is pretty badly named, I guess. It's simply a cache. Your implementation is fine, you just need to pass `$test` to your other method if you want to use it there.

**Comment by iamsyh** [comment]
> 
> 
> The `Environment` is pretty badly named, I guess. It's simply a cache. Your implementation is fine, you just need to pass `$test` to your other method if you want to use it there.

hi! apologies for the late reply! ahh okay okay noted..

thank you so much for answering so promptly!
