### ISSUE TITLE
Is possible to share data from main process to workers?

### ISSUE THREAD

**Issue by aloumpas** [amphp/parallel#137]
I would like to know is it possible to create, lets say an array, on the main process and then read this inside workers without copying the entire array inside worker. Also i would like to know if it possible from workers to write on shared variables on the main process

**Comment by danog** [comment]
My amphp IPC library might help vere: github.com/danog/ipc

**Comment by trowski** [comment]
I believe this question has been answered, so I'm closing it. Please open a new issue if you have any further questions. 👍
