### ISSUE TITLE
Promise\wait() Time-consuming question.

### ISSUE THREAD

**Issue by amourjun** [amphp/parallel#142]
In my local test, the execution time of the Promise\wait() method without additional logic is spent
About 100ms. 
Is this normal? Is this the cost of context switching?

Regards.

**Comment by kelunik** [comment]
What exactly are you awaiting?

**Comment by amourjun** [comment]
> What exactly are you awaiting?

```
<?php

use Amp\Promise;
use function Amp\ParallelFunctions\parallelMap;

$start = microtime(true) ;
$values = Promise\wait(parallelMap([0, 0], function ($time) {
    \sleep($time); // a blocking function call, might also do blocking I/O here
    return $time * $time;
}));
$end = microtime(true) ;
$duration =  ($end - $start) * 1000;
var_dump($duration);
```
This is the code I execute under MacOS. No other time-consuming logic is executed in the function. However, the duration output is about 100ms.

**Comment by amourjun** [comment]
> What exactly are you awaiting?

Is it only suitable for concurrent functions with a delay of more than 1s, but not for functions within 100ms?

**Comment by kelunik** [comment]
There will be some overhead for starting the child process (initial latency), and some overhead per task due to communication with the child process (job latency).

The exact numbers will depend on your OS and system specs.

Note that while the latency might be higher, it doesn't block the event loop.

**Comment by amourjun** [comment]
I find this time-consuming is higher when more processes are started. This is not suitable for my application, I need to return within a few hundred milliseconds, but it is all spent in the process of waiting.

Thanks for the answer.
