### ISSUE TITLE
Example with post data

### ISSUE THREAD

**Issue by haffoudhi** [amphp/parallel#149]
Hey, 
I m new to amphp/parallel, I can't find an example of Worker\enqueueCallable with post data, instead of file_get_contents url.
I need to send data to url and receive the response. I m sending a lot of data, so GET is not a solution.
Can you share an example of post data, preferably with amphp/http-client?

**Comment by kelunik** [comment]
You have already discovered the correct library to use: amphp/http-client. You can find such examples in its repository in the examples directory.

**Comment by haffoudhi** [comment]
Thanks!
