### ISSUE TITLE
Awaiting on worker pool to be empty.

### ISSUE THREAD

**Issue by whataboutpereira** [amphp/parallel#152]
Using amp/parallel v2.

Is there a more sensible way to wait/await for the worker pool to become empty? Maybe a helper function hidden somewhere?

Currently using:

```
while(($pool->getWorkerCount() - $pool->getIdleWorkerCount()) > 0) {
	delay(0.1);
}
```

A helper function in the default pool along the lines of getActiveWorkerCount() `$pool->getWorkerCount() - $pool->getIdleWorkerCount()` would also be a nice addition. :)

**Comment by trowski** [comment]
Why do you want to wait for a worker poll to be empty? Generally, you should be enqueuing the task to the pool and the task will be run when the pool has an idle worker. There is no need to wait for the pool to be idle.

**Comment by whataboutpereira** [comment]
I believe it was to not push 129k tasks to the pool at once. :)

**Comment by whataboutpereira** [comment]
I believe it had to do with shutting down my script after the pool had emptied.

**Comment by trowski** [comment]
Calling `shutdown()` on the pool will wait for any pending task to complete before shutting down.
