### ISSUE TITLE
parallel-functions

### ISSUE THREAD

**Issue by X-821** [amphp/parallel#153]
Hi

I'm using the example in amps website and getting error
Here is my code and the error I got:

Code:
$values = Promise\wait(parallelMap([1, 2, 3], function ($time) {
    \sleep($time); // a blocking function call, might also do blocking I/O here
    return $time * $time;
}));

Error:
call_user_func_array(): Argument #1 ($callback) must be a valid callback, no array or string given
public_html/s/vendor/laravel/serializable-closure/src/Serializers/Native.php

**Comment by trowski** [comment]
I believe you're looking for [`amphp/parallel-functions`](https://github.com/amphp/parallel-functions), however that library will no longer be supported in the future.
