### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by rybakit** [amphp/parallel#19]
Got this error recently:
```
Argument 3 passed to Amp\Parallel\Worker\TaskException::__construct() 
must be of the type integer, string given, 
called in .../vendor/amphp/parallel/lib/Worker/Internal/TaskFailure.php on line 54
```
This happens because `PDOException::getCode()` can return a string.

**Comment by kelunik** [comment]
Thanks for reporting, #20 should fix this.

**Comment by kelunik** [comment]
I think the actual fix for v0.2 should be to simply not reuse the exception code of the parent exception, but instead just use `0` there and remove the parameter from the constructor.

**Comment by bwoebi** [comment]
I agree here. The code is just part of the parent exception, it has no business in the wrapping exception.

**Comment by kelunik** [comment]
But changing that now would be a BC break, so let's do it for v0.2 only.
