### ISSUE TITLE
Don't forward exception codes

### ISSUE THREAD

**Issue by kelunik** [amphp/parallel#21]
This is a tracking issue for v0.2, so we don't forget about it. Exception codes shouldn't be passed to the new exception's constructor, but only be in the previous exception.

See https://github.com/amphp/parallel/issues/19.

**Comment by kelunik** [comment]
This can be implemented in `master` now, as we have to break BC for the new process library anyway.

**Comment by trowski** [comment]
The code is now included in the message of the exception thrown in the parent context instead of being passed to the constructor. See commit 26e826a.
