### ISSUE TITLE
Cannot acquire lock?

### ISSUE THREAD

**Issue by RobberPhex** [amphp/parallel#24]
There is only [`release` method](https://github.com/amphp/parallel/blob/c7294da60d0402db8ea60060bc91e94d19a013c5/lib/Sync/Lock.php#L42), haven't `acquire` method?

**Comment by kelunik** [comment]
`Lock` is just the lock handle after acquiring. There's [`Mutex::acquire()`](https://github.com/amphp/parallel/blob/2e9a29ae1c64425d423341e0fa8eef0f4b073e20/lib/Sync/Mutex.php#L23) for acquiring a lock.
