### ISSUE TITLE
Using worker in php fpm

### ISSUE THREAD

**Issue by GordonGuenther** [amphp/parallel#26]
To reply to a user request faster, i want to start multiple parallel jobs, wait for all jobs to finish, collect all responses of the jobs and return them to the user. For this requirement i'd like to use this library.

As a start I tried the worker and worker-pool example within my php-fpm process and got the following error: "Undefined constant 'STDERR' in /var/www/vendor/amphp/parallel/lib/Process/ChannelledProcess.php on line 82" 

When i define STDERR myself, i get the next error:
"Uncaught Amp\Parallel\Sync\ChannelException: Invalid header received: [...] in /var/www/vendor/amphp/parallel/lib/Worker/AbstractWorker.php on line 172"

I'm running the code in a docker image php:7.1-fpm-alpine with only a few additional extensions. Non of the suggested, but apparently not required, extensions for threads or forks have been installed.

Is this library restricted to cli use? The readme doesn't state anything like this.

**Comment by kelunik** [comment]
Currently it is restricted to CLI and PHPDBG, yes. There's no explicit check for that though. For usage outside of it, we'd need to find the correct binary to use.

https://github.com/amphp/parallel/blob/0ef74413afd6370d3c348f719d527e3155694504/lib/Process/ChannelledProcess.php#L46-L48

**Comment by GordonGuenther** [comment]
Is it possible to start the task-processes with php-cli instead of a new php-fpm and still run the loop in php-fpm?

For testing i replaced the \PHP_BINARY in parallel/lib/Process/ChannelledProcess.php:48 with '/usr/local/bin/php'. Now i get the error:
Uncaught Amp\Parallel\PanicError: Uncaught exception in execution context of type "TypeError" with message "Return value of Amp\Parallel\Worker\Internal\Job::getTask() must be an instance of Amp\Parallel\Worker\Task, instance of __PHP_Incomplete_Class returned" in /var/www/vendor/amphp/parallel/lib/Worker/AbstractWorker.php on line 172

**Comment by kelunik** [comment]
That means your `Task` isn't autoloadable, but it has to be. We should add a better error message for that.

**Comment by GordonGuenther** [comment]
Okay, nice to know. Now it works.

But how do i get this patched in ChannelledProcess.php? A pull request just replacing the one line:
$command = \escapeshellarg(\PHP_BINARY === '/usr/local/sbin/php-fpm' ? '/usr/local/bin/php' : PHP_BINARY) . $options . $separator . \escapeshellarg($path);
probably wouldn't be accepted, would it? ;-)

It would be nice, if i could optionally inject the path to my php binary somehow and only use \PHP_BINARY as a fallback.

**Comment by GordonGuenther** [comment]
I run into the next problem, if i start to put some more logic into the worker-pool example, but this is a different issue.

This issue seems to be resolved, i will use cweagans/composer-patches to patch the above line into amphp/parallel on execution of composer.

**Comment by kelunik** [comment]
@GordonGuenther We could definitely accept a pull request, but not like that, yes. But a environment variable like `PHP_CLI_BINARY` could work.

**Comment by GordonGuenther** [comment]
That's a good idea. I added a pull request.

**Comment by trowski** [comment]
Closing this as automatic detection of the PHP binary path (and the ability to provide a custom binary path) has been implemented in 0.2. You should now be able to launch process/workers in any SAPI without issue.
