### ISSUE TITLE
Can't use objects instances inside Thread::spawn

### ISSUE THREAD

**Issue by afym** [amphp/parallel#29]
I am using the following sample about threads [https://github.com/amphp/parallel/blob/master/examples/thread.php] 

And works fine. However, when I try to use an object inside spawn, is not working.

## Without object instance
```php
<?php

require(dirname(__DIR__) . '/autoload.php');

use Amp\Loop;
use Amp\Parallel\Threading\Thread;
use Amp\Delayed;

Loop::run(function () {
    $timer = Loop::repeat(1000, function () {
        static $i;
        $i = $i ? ++$i : 1;
        print "Demonstrating how alive the parent is for the {$i}th time.\n";
    });
    try {
        // Create a new child thread that does some blocking stuff.
        $context1 = Thread::spawn(function () {
            echo "inside spawn \n";
            sleep(1);
            echo "end spawn \n";
        });

        yield new Delayed(2000);
        yield $context1->send([1]);
    } finally {
        Loop::cancel($timer);
    }
});
```

The output is : 

```
$ zts-php modules/Jobs/scripts/test.php
inside spawn 
Demonstrating how alive the parent is for the 1th time.
end spawn 
```

## With object instance
```php
require(dirname(__DIR__) . '/autoload.php');

use Amp\Loop;
use Amp\Parallel\Threading\Thread;
use Amp\Delayed;

class A {
    public function get() {
        return "a value";
    }
}
Loop::run(function () {
    $timer = Loop::repeat(1000, function () {
        static $i;
        $i = $i ? ++$i : 1;
        print "Demonstrating how alive the parent is for the {$i}th time.\n";
    });
    try {
        // Create a new child thread that does some blocking stuff.
        $context1 = Thread::spawn(function () {
            echo "inside spawn \n";
            $a = new A();
            echo $a->get();
            echo "end spawn \n";
        });

        yield new Delayed(2000);
        yield $context1->send([1]);
    } finally {
        Loop::cancel($timer);
    }
});
```

The output is : 

```
$ zts-php modules/Jobs/scripts/test.php
inside spawn 
Demonstrating how alive the parent is for the 1th time.
```

Some additional information:

- Working with centos 7.3
- Working with PHP 7.2
- Working with Zend Framework
- Working with pthreads.so extension

Any suggestion? I think that my class A must have some interface or extends from other class build on the Amp package but I can not find any documentation.

**Comment by afym** [comment]
Hi there. I could find the answer for my problem. What I did was add the autoload.php require inside spawn function.

use Amp\Loop;
use Amp\Parallel\Threading\Thread;
use Amp\Delayed;

Loop::run(function () {
    $timer = Loop::repeat(1000, function () {
        static $i;
        $i = $i ? ++$i : 1;
        print "Demonstrating how alive the parent is for the {$i}th time.\n";
    });
    try {
        // Create a new child thread that does some blocking stuff.
        $context1 = Thread::spawn(function () {
            require(dirname(__DIR__) . '/autoload.php');
            $result = $container->get('My_Custom_Service');
            print($result->findAll());
            echo "inside spawn \n";
        });

        yield new Delayed(2000);
        yield $context1->send([1]);
    } finally {
        Loop::cancel($timer);
    }
});

**Comment by trowski** [comment]
Sorry for the delay in responding, been very busy lately.

Classes used within `Thread::spawn()` must be autoloadable. That is, class definitions (as well as function and constant definitions) are not inherited from the parent. When using composer this is not an issue, as the composer autoloader is automatically included again. This should be made clear in the documentation.

If you are re-including the composer autoloader that is unnecessary - it is automatically done for you.
