### ISSUE TITLE
Undefined Constant STDERR in parallel/lib/Context/Process

### ISSUE THREAD

**Issue by ylin0603** [amphp/parallel#34]
I'm using php-fpm7.0.22 + nginx 
when I tried to execute this piece of code demo in artax documentation, it showed the error message as title.

```php
        foreach ($requests as $request) {
            $promises[] = call(function () use ($defaultClient, $request) {
                $response = yield $defaultClient->request($request);
                $body = yield $response->getBody();
                return $body;
            });
        }
        $response = wait(all($promises));
```

I think this issue is relate to #26 . and I'm using artax 3.0.13 and parallel ^0.2. Is this issue not resolved completely?

**Comment by kelunik** [comment]
I guess this is an oversight, yes. There are two options: We define `STDERR` and `STDOUT` if they're not defined, or we use `error_log` instead.

**Comment by kelunik** [comment]
https://github.com/amphp/byte-stream/releases/tag/v1.2.2 fixes this which can be pulled via `composer update`. Thanks for your report.
