### ISSUE TITLE
Not able to locate PHP Binary on macOS

### ISSUE THREAD

**Issue by irazasyed** [amphp/parallel#35]
I was trying this library today with brew installed PHP packages and I ended up with this exception:

```Could not locate PHP executable binary```

Turns out, the `getenv('PATH')` returns false.

I tried Symfony's [PhpExecutableFinder](https://github.com/symfony/process/blob/master/PhpExecutableFinder.php) and it works fine and is able to locate the binary.

Would it be possible to either use Symfony's PHPExecutable Finder or make changes to the existing code to do what Symfony does to locate the binary?

Thanks!

**Comment by trowski** [comment]
@irazasyed Can you please try replacing `Amp\Parallel\Context\Process::locateBinary()` on your local copy with the following implementation:

```php
private static function locateBinary(): string {
    $executable = \strncasecmp(\PHP_OS, "WIN", 3) === 0 ? "php.exe" : "php";

    $paths = \array_filter(\explode(\PATH_SEPARATOR, \getenv("PATH")));
    $paths[] = \PHP_BINDIR;
    $paths = \array_unique($paths);

    foreach ($paths as $path) {
        $path .= \DIRECTORY_SEPARATOR . $executable;
        if (\is_executable($path)) {
            return self::$binaryPath = $path;
        }
    }

    throw new \Error("Could not locate PHP executable binary");
}
```

Let me know if that works!

**Comment by kelunik** [comment]
How's your path variable called? `Path`? https://github.com/symfony/process/blob/d34b43a0f1e874cced7c0fdede5daf2846041838/ExecutableFinder.php#L68

**Comment by irazasyed** [comment]
@trowski That worked 👍 

@kelunik `PATH` - It doesn't seem to return any value if I execute the script but on CLI it works fine. Maybe somewhere it's being unset or something (Not really sure how it works behind the scene - I'm using Laravel Valet BTW).

P.S. Sorry for the delay in responding. Been away! But thanks for looking into it.

**Comment by kelunik** [comment]
@irazasyed I guess that's using Nginx under the hood? I think Nginx unsets all environment variables and only has a whitelist of some variables it exposes. As long as `PHP_BINDIR` works, that's fine. If that doesn't work, people have to explicitly set `PATH` then in such environments.

**Comment by irazasyed** [comment]
@kelunik Oh I see. Yes, It uses Nginx.

So I guess you guys can apply these changes so I can composer update it?

Thanks!

**Comment by gijo-varghese** [comment]
@trowski I'm still having this issue (using the latest version) in macOS with Nginx using Local by Flywheel. Any workaround?

**Comment by kelunik** [comment]
You can call `\putenv('PATH', ...);` at the beginning of your script including the path to your PHP executable.

**Comment by gijo-varghese** [comment]
@kelunik Thanks, that did the trick!

Do you think this will happen only for macOS? Or is it specific to Nginx? I'm developing a WordPress plugin which will be used by many web servers like Apache, Nginx, LiteSpeed, etc

**Comment by gijo-varghese** [comment]
I tested with Kinsta hosting. They also don't have `PATH` env variable

**Comment by kelunik** [comment]
What are you trying to do with parallel there? I'd generally recommend to avoid parallel within Web requests inside Apache / php-fpm.

**Comment by gijo-varghese** [comment]
@kelunik it's a WordPress plugin will self-host Google Fonts. HTML is parsed and all fonts files are downloaded. For example, it will open https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&family=Roboto:wght@400;500 and download all woff2 files. 

Later these files are injected and HTML page is cached. So these parallel downloads don't occur frequently.

**Comment by kelunik** [comment]
If you only need concurrent downloads, I'd recommend you to use amphp/http-client instead of amphp/parallel. It uses non-blocking IO instead of multiple processes, so doesn't have these PATH problems.

**Comment by gijo-varghese** [comment]
@kelunik Thanks. I'll check it out. I tried https://github.com/jmathai/php-multi-curl and it seems to be working well.

**Comment by kelunik** [comment]
Multi-Curl will probably give you similar results, yes, but has obviously a requirement on `ext-curl`.

**Comment by gijo-varghese** [comment]
@kelunik yes, I'm still looking for alternatives.`amphp/http-client` doesn't have any such dependencies right?

**Comment by kelunik** [comment]
Yes.
