### ISSUE TITLE
Multicore support

### ISSUE THREAD

**Issue by umbri** [amphp/parallel#37]
Currently I am developing something like [master -> workers](https://github.com/amphp/aerys/blob/master/lib/WatcherProcess.php).

1. Why in ```aerys``` you use ```proc_open``` for spawn workers, and not [Thread](https://github.com/amphp/parallel/blob/master/lib/Context/Thread.php) ?

2. Is [Thread](https://github.com/amphp/parallel/blob/master/lib/Context/Thread.php) using multicore on spawn ?

3. Why ```aerys``` don't use [amphp/process](https://github.com/amphp/process) or [amphp/parallel](https://github.com/amphp/parallel) for ```[master -> workers]```

4. Why from [amphp/parallel > v0.2](https://github.com/amphp/parallel) was removed ```fork()``` support ? 

5. Is there, may be, advantages to use ```proc_open``` vs ```fork``` ?

**Comment by kelunik** [comment]
1. `proc_open` is available everywhere, while threads are not. With (3) we could automatically choose one environment, but there aren't too much benefits of threads over processes.

2. As far as I know it does, yes. But you can simply test that.

3. I think @trowski refactored it at some point, but not sure why we didn't merge it. Maybe he can give more insights here.

4. See release notes.

> The forking context has been completely removed. Forking the entire process state proved to be too error-prone to be useful as a general-purpose parallel execution context.

5. Yes, there are, e.g. not inheriting all static variables, registered shutdown functions, ...

**Comment by trowski** [comment]
Using `amphp/process` is on the todo list. I never finished the refactor I started… don't remember why. I believe the process code in this lib was written before `amphp/process` existed, so it just has never been updated.
