### ISSUE TITLE
Development tags

### ISSUE THREAD

**Issue by brendt** [amphp/parallel#4]
Would there be any chance this library (and its amp dependencies) could be tagged following semver guidelines? The only way I can safely add this library without worrying about BC breaking changes is to manually specify a commit, and an minimum-stability of dev.

```json
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require" : {
        "amphp/loop": "dev-master#302a5c714c2700d32ca9444be09f21b2835b213f",
        "amphp/amp": "2.0.x-dev#72378e2b82d9f1dee6b93de2bee8aa138e7f67e1",
        "amphp/parallel": "0.1.x-dev#9cc70c1f86bf8ffa8ca744e40702502410b733f0",
        "async-interop/promise": "^0.4"
    }
```

This is the only configuration I could find which works for me and is safe. Any suggestions as to improve this would be welcome.

**Comment by kelunik** [comment]
Yes, they will get tagged, but only after Amp v2 is tagged, which will be soon. You can help by taking care of the outstanding issues there: https://github.com/amphp/amp/issues

**Comment by brendt** [comment]
Ok, thanks for the reply, let's hope it'll be done soon!
