### ISSUE TITLE
Using object and its dependencies vs problem with serialization

### ISSUE THREAD

**Issue by bartek9007** [amphp/parallel#49]
I was trying out [worker pool](https://github.com/amphp/parallel/blob/master/examples/worker-pool.php) example. It works very well when using simple things, like php function or simple anonymous function without binding them with any existing object. Could you please tell if while using parallel it's possible to work with objects and its dependencies? 

There is always problem with serialization. I have read the note about `opis/closure` library and restrictions about serializing. I was trying to wrap my function call in new SerializableClosure(), but then I get exceptions as following:

```
[Amp\Parallel\Context\ContextException]                                           
  The context stopped responding, potentially due to a fatal error or calling exit  
                                                                                    
  [Amp\Parallel\Sync\ChannelException]                   
  The channel closed unexpectedly. Did the context die?
```

Here there is an example of what I am trying to execute:

```
class Something {

public function test($item)
    {
        var_dump($item);
    }


public function execute() {

            $tasks = [
                 new BlockingTask(new SerializableClosure(function ($item) {
                    $this->test($item);
                } ), 5)
            ]
           

            Loop::run(function () use (&$results, &$tasks) {
            $timer = Loop::repeat(200, function () {
                printf(".");
            });
            Loop::unreference($timer);
            $pool = new DefaultPool;
            $coroutines = [];
            foreach ($tasks as $task) {
                $coroutines[] = function () use ($pool, $task, &$results) {
                    $result = yield $pool->enqueue($task);
                    $url = $task->getArgs()[0];
                    //printf("\nRead from %s: %d bytes\n", $url, strlen($result));
                    $results[$url] = $result;
                };
            }
            $coroutines = array_map(function (callable $coroutine): Coroutine {
                return new Coroutine($coroutine());
            }, $coroutines);
            yield \Amp\Promise\all($coroutines);
            return yield $pool->shutdown();
        });
        echo "\nResult array keys:\n";
        echo var_export(array_keys($results), true);
    }
}
```

Of course tricky part is that with building new `BlockingTask()`. Is it generally possible - I mean pass as callable to parallel concrete class method and run it successfully?

**Comment by rybakit** [comment]
@bartek9007 As you've noticed, the object/closure serialization is very limited in PHP (`PDO` is a good example), so I would not recommend doing that. Instead, I would pass the execution context to a forked process, so it can use whatever service it needs to do its job. Here is how I implemented it:

* [Job runner example](https://github.com/tarantool-php/jobqueue/blob/07b4d9c7cd8507d425365766db726f1ce32f6921/src/Runner/Amp/ParallelRunner.php#L48-L52)
* [Blocking task example](https://github.com/tarantool-php/jobqueue/blob/07b4d9c7cd8507d425365766db726f1ce32f6921/src/Runner/Amp/GenericTask.php#L31-L34)
* [Demo app](https://github.com/tarantool-php/jobserver)

**Comment by kelunik** [comment]
@bartek9007 `opis/closure` automatically wraps closures, but that's only part of [`amphp/parallel-functions`](https://github.com/amphp/parallel-functions), not `amphp/parallel` itself. For `amphp/parallel` to work, everything you pass between the execution contexts needs to be serializable. Instead of passing the full services around, I'd just pass the job data around and create new services in the child processes.

**Comment by kelunik** [comment]
It seems like all questions have been answered. If not, please respond with further questions, the issue can always be re-opened. :+1:
