### ISSUE TITLE
Custom Environment

### ISSUE THREAD

**Issue by rybakit** [amphp/parallel#5]
I would like to share non-serialisable objects across workers/threads. What is the recommended way to do so? Do I need to create my own [/bin/worker](https://github.com/amphp/parallel/blob/master/bin/worker#L39), [WorkerProcess](https://github.com/amphp/parallel/blob/master/lib/Worker/WorkerProcess.php#L13), [WorkerThread](https://github.com/amphp/parallel/blob/master/lib/Worker/WorkerThread.php#L15) and [WorkerFactory](https://github.com/amphp/parallel/blob/master/lib/Worker/DefaultWorkerFactory.php#L20) or is there a more simple way of creating a new (or populating existing) environment?

**Comment by kelunik** [comment]
Why do you need to share such an object?

**Comment by rybakit** [comment]
I try to implement a job queue with amphp/parallel. The job queue has a runner (worker) which is  responsible to execute jobs. The runner and jobs are designed to share the same execution context.
This context can vary based on a job queue configuration, but literally it can hold instances of any type (including resources, closures, anonymous classes, etc). For example, by default, runners and jobs share the same logger and queue instances.

I can recreate these instances in [Task::run()](https://github.com/amphp/parallel/blob/master/lib/Worker/Task.php#L18) on every call via custom (serializable) factories, but seems like an environment object suites better in this case, as I can build context objects only once per worker and simply share them via the task environment.

**Comment by kelunik** [comment]
Sharing resources and closures with multiple processes isn't really possible. PHP is shared nothing. But I have to say I'm not really familiar with `amphp/parallel` yet. I'll defer to @trowski.

**Comment by rybakit** [comment]
> Sharing resources and closures with multiple processes isn't really possible. PHP is shared nothing.

True. That is why I want to recreate them per process and then share with all tasks running by this process via environment (check [this line](https://github.com/amphp/parallel/blob/master/bin/worker#L39)). I'm just looking for an easy way to inject my resources to this environment (or replace it with my custom one). For example, like it's done for other services:

```php
Loop::setState(TASK_ENV_IDENTIFIER, $myEnvironemnt);
```
https://github.com/amphp/parallel/blob/master/lib/Worker/functions.php#L64-L75

**Comment by trowski** [comment]
`Environment` is just a simple "global" key/value store with an optional TTL (expiration) on keys. If you want to share something that cannot be serialized amongst tasks, it should be stored in the `Environment` object given to `Task::run()`. Generally the easiest way to do this is to have the run method of each task check for the existence and create it if necessary.

```php
<?php

class ExampleTask implements Task {
    const DB_KEY = ExampleTask::class . "-db";

    public function run(Environment $environment) {
        $db = $environment->get(ExampleTask::DB_KEY);
        
        if ($db === null) { // DB connection didn't exist.
            $db = new Database; // Unserializable object.
            $environment->set(ExampleTask:: DB_KEY, $db);
        }
        
        // Use $db for task.
        
        return $serializableTaskResult;
    }
}
```

Note that the instance of `Environment` is per-worker, so in this example there will be a database connection in each worker.

If you want to create a custom implementation of `Environment`, you'll then have to create a copy of `bin/worker` and your own instance of `Worker` and `WorkerFactory` creating a worker using that PHP script. I may consider making this sort of thing easier to implement in a future version (will be tagging this lib after Amp v2 is officially released)… but generally `BasicEnvironment` should do everything necessary.

**Comment by rybakit** [comment]
@trowski Thank you for the explanation and links. Actually, I was also thinking about checking environment for the existence and create objects in Task::run() if they miss. And, indeed, it seems like the easiest way to achieve what I need. Thanks :)
