### ISSUE TITLE
[SOLVED] Error using $output from Symfony Command

### ISSUE THREAD

**Issue by TomFreudenberg** [amphp/parallel#53]
Hi, thanks for your effort and sharing this library.

I have optimized some of our Symfony CLI apps with this parallels extension. So far all works, but I can't use the Symfony Output anymore.

  

Simple example for a task:

``` php
<?php

use Amp\Parallel\Worker\Environment;
use Amp\Parallel\Worker\Task;

class MyTask implements Task {

  private $output;

  public function __construct($output) {
    $this->output = $output;
    $this->output->writeln("OUTPUT INSIDE CONSTRUCT WORKS");
  }

  public function run(Environment $environment) {
    echo "THIS WORKS\n";
    $this->output->writeln("OUTPUT INSIDE RUN BREAKS");
    $sleep = rand(1, 3);
    sleep($sleep); // Blocking call in thread.
    return 0
  }

}
```

  

And my Symfony Command looks like (I tried to simplify as much as possible):

``` php
<?php

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;

use Amp\Loop;
use Amp\Parallel\Worker\DefaultPool;

use MyTask;

class MyCommand extends Command {

  protected function configure(){
    $this->setName("Process:Amp")
         ->setDescription("This will run some parallel processes.")
         ->addArgument('count', InputArgument::REQUIRED, 'Number of concurrent pool processes.');
  }

  protected function execute(InputInterface $input, OutputInterface $output){

    $output->writeln('START COMMAND ...');

    // We can first define tasks and then run them
    $tasks = [
      new MyTask($output),
      new MyTask($output),
      new MyTask($output),
      new MyTask($output),
      new MyTask($output),
    ];

    try {

      // get parameters
      $cnt_parallels = $input->getArgument('count');

      $pool = new DefaultPool($cnt_parallels);

      foreach ($tasks as $task) {
        $pool->enqueue($task);
      }

      // Event loop for parallel tasks
      Loop::run(function () use (&$pool) {
        return $pool->shutdown();
      });

    }
    finally {

      $output->writeln('WELL, COMMAND Finally reached!');

    }

  }

}
```

  

The above will immediately stop but not shown any exception.

If changing the loop code with Coroutines then following exception is shown and formatted via Symfony:

> In TaskFailure.php line 55:
> 
> Uncaught Symfony\Component\Console\Exception\RuntimeException in worker with message "Unable to write output." and code "0"

  

Thanks for some hints or solution in advance
Cheers, Tom

**Comment by TomFreudenberg** [comment]
When var_dumping in _vendor/symfony/console/Output/StreamOutput.php_ the content of

`$this->stream` in `function doWrite($message, $newline)`,

then normally returns:

> resource(57) of type (stream)

but when calling from inside `run`:

> int(0)

  

Any idea what happens there?

**Comment by kelunik** [comment]
@TomFreudenberg You can't directly write to STDOUT in workers, because STDOUT is used for the IPC with the parent. Until we change that, you either need to write to STDERR or write to your own logging channel, e.g. a file. `echo` / `print` works, because we use output buffering to redirect those calls to STDERR and the parent just forwards the child's STDERR to its own STDERR.

**Comment by TomFreudenberg** [comment]
Hi Neklis @kelunik 

understood!

Sorry for maybe silly question, but: 

Do you have any idea how to define a Symfony Output which will "print the information to console" while task / loop is running?

Thanks for your help
Tom

**Comment by kelunik** [comment]
You can use a [`new StreamOutput(STDERR)`](https://github.com/symfony/console/blob/master/Output/StreamOutput.php) as far as I can tell.

**Comment by TomFreudenberg** [comment]
Hi Niklas @kelunik 

When I add

```php
$this->output = new \Symfony\Component\Console\Output\StreamOutput(STDERR);
```

into `function run()` from MyTask it will work!

It does not work if I create that `StreamOutput` object outside or in `__constructor()`

Do you know why?

`$this->stream` will be emptied to `int(0)` when creating and setting the `$output` outside of the `MyTask` `run function`?

**Comment by TomFreudenberg** [comment]
Hi Niklas @kelunik 

one additional question:

Is it possible to not use STDOUT for channel / IPC communication but some extra or none?

If yes, do you have a hint about "how"

  

Just to give you a better understanding for my needs:

In my case, there is no communication necessary between the parent and child threads. I just want run a number of the same command function (within external processes) in parallel. The function will log and handle its errors etc. by itself. I do not return a value or check that in loop.

  

Thanks for your help
Tom

**Comment by kelunik** [comment]
It's converted to 0, because resources aren't serializable. If you don't need any IPC, you can use child processes manually with `amphp/process`.

**Comment by rybakit** [comment]
> It's converted to 0

@kelunik could you point to the code, where this conversation happens?

**Comment by TomFreudenberg** [comment]
Hi Niklas @kelunik 

I was looking for `pthreads` but in case that this is not available per default, I looked for other solutions with less maintenance. Compiling `php` and `pthreads` always by ourselfs or trusting some ppa from Ondřej Surý, is not what we are willing to do.

So I looked on amp/parallel.

> If you don't need any IPC, you can use child processes manually with amphp/process

The issue with amphp/process is, that I just can run external programs from that. My need is to run a internal function more than once (like threads).

Sure, I could create a SymfonyCommand to call for just one file and then call that in a loop. But in case that we need a lot of settings during the function (like database connection etc.) I had to create some huge command line arguments or serialization of values. This is for what I like the _comfort_ of amp/parallels.

I guess, amp/process is too _rudimental_ for that case.

**Comment by TomFreudenberg** [comment]
Hi Niklas @kelunik 

Last comment here - a bit offtopic -

I tried to send an initialized PDO object to my Task function, but that won't work either. Looks like that those kind of vars (objects) can't be handled by IPC / PARALLELS either?

Seems to me like I am doing the wrong things with the wrong toolkits :-(

**Comment by rybakit** [comment]
@TomFreudenberg PDO objects can't be serialized.

**Comment by TomFreudenberg** [comment]
Hi Eugene @rybakit 

thanks for Feedback. Yes I understood.

Is it correct to say that the `function run()` of my `Task` class would be handled inside the new (separated) en-queued process.

If so, I can understand now, why and where to define the necessary (complex) objects in that function.

**Comment by kelunik** [comment]
@rybakit PHP does that internally during serialize.

@TomFreudenberg PHP is shared nothing. Everything you share needs to be serializable and is copied not shared. In case of database connections, you need to establish a new connection in the child / thread.

**Comment by TomFreudenberg** [comment]
@kelunik Thanks for help and clarification
