### ISSUE TITLE
Support delayed port access (e.g. due to firewalls)

### ISSUE THREAD

**Issue by c33s** [amphp/parallel#73]
@kelunik [told][1] me to open a ticket here. 

> Please open an issue at https://github.com/amphp/parallel for the infinite loop and https://github.com/amphp/process for the ports if you want.

its quite a while but as the [problem with box][2] was easy solvable by using the `--no-parallel` option i simply forgot until i hit the problem again with [fink][3].

i am not sure where to write which info, it feels i would post the same text in parallel and process as i haven't used amphp directly but only tools which use it, i don't know the internals.

if i run fink it simply gets stuck forever on a windows system with a firewall.
```
php fink.phar https://getcomposer.org
```
![console](https://user-images.githubusercontent.com/649209/53842638-58e17a80-3fa0-11e9-8081-d86aeaa6e7c2.png)

if my firewall is in learning mode, it ask me to allow `ampXXXX.tmp` a local connection.

![firewall-dialog](https://user-images.githubusercontent.com/649209/53842532-1881fc80-3fa0-11e9-8a39-395fc8b6375e.png)

after allowing it, the connection monitor show the following:

![connections](https://user-images.githubusercontent.com/649209/53842598-3d766f80-3fa0-11e9-9e38-b5c0c62efb04.png)

this 3 php and amp processes stay there forever in an infinite loop and are doing nothing (no more as the initial 22 bytes are sent or received). 

if i run the firewall in allow all mode (which sadly makes no sense at all), it works without a problem. 

so it looks like amphp has a problem if the port is not instantly accessible but delayed by a firewall learning mode dialog. 
as the amp process names are randomly generated it is not possible to precreate the firewall rules.
having some kind of check if ports can be accessed and if not some kind of fallback could be a solution. a slow synchronous processing is still faster as a infinite do nothing processing :)

[1]: https://github.com/humbug/box/issues/166#issuecomment-385187646
[2]: https://github.com/humbug/box/issues/166
[3]: https://github.com/dantleech/fink/issues/57

**Comment by kelunik** [comment]
I'm not sure how we can test this, so I'm currently closing this as not planned.

**Comment by trowski** [comment]
The IPC connect time is tunable in `v2`. Increasing the timeout beyond the default 5 seconds will help with this issue.
