### ISSUE TITLE
Support customizing the sub-process options

### ISSUE THREAD

**Issue by Zerzera** [amphp/parallel#75]
I run PHP with `-c \some\location\php.ini`,  but their's no way to influence the options which handles the process creation.

In `\Amp\Parallel\Context\options::75` there's a hard coded array of options, it would be nice to have a setter for those options.

**Comment by kelunik** [comment]
This is now implemented in https://github.com/amphp/parallel/commit/32ff641987fe041a756a750d01b03ddaa2eda546.
