### ISSUE TITLE
The channel closed unexpectedly. Did the context die? | Used in Rest API

### ISSUE THREAD

**Issue by edcelvista** [amphp/parallel#84]
** Error **
Type: ` Amp\Parallel\Sync\ChannelException`
Message: `The channel closed unexpectedly. Did the context die?`
File: `/vendor/amphp/parallel/lib/Sync/ChannelledStream.php`

**Comment by kelunik** [comment]
Without any further information, we can't help you. What's your code to trigger this?

**Comment by edcelvista** [comment]
The issue has been resolved and found out that it's not related to this library. 

This library help us a lot. Thanks so much!

**Comment by kelunik** [comment]
I'm glad to hear that. Would be cool to see some blog posts on how other people use Amp and its libraries. :-)
