### ISSUE TITLE
pthreads replacements

### ISSUE THREAD

**Issue by irkallacz** [amphp/parallel#86]
Hi. As mentioned in [php manual](https://www.php.net/manual/en/intro.pthreads.php), pthreads extension will no longer be maintained after PHP 7.4 and we should be using [parallel](https://www.php.net/manual/en/intro.parallel.php) extension instead.

Will there be a support for parallel extension in this project in the future?

**Comment by trowski** [comment]
The parallel extension has been supported since [v1.2.0](https://github.com/amphp/parallel/releases/tag/v1.2.0). 😁

pthreads support will be deprecated in v1.3.0.

**Comment by irkallacz** [comment]
Really good to hear that!

I swear, that I dig through the whole documentation, but I didn't find find anything. After your answer I look at the code and examples, and it is crystal clear now. 

Thanks a lot.

**Comment by trowski** [comment]
Documentation is lacking a bit for this library. Hopefully I can get some time to improve it soon!
