### ISSUE TITLE
Assertion failed: (zend_gc_refcount(&(ht)->gc) == 1) when using parallel

### ISSUE THREAD

**Issue by autaut03** [amphp/parallel#88]
Hey there. I'm trying to simply run the [example code](https://github.com/amphp/parallel/blob/master/examples/parallel-extension.php) for parallel-based parallelism and it doesn't work. Right after `$context->join()` I get the assertion failure that crashes the process:
```
Assertion failed: (zend_gc_refcount(&(ht)->gc) == 1), function shutdown_executor, file /Users/alexwells/.phpbrew/build/php-7.4.1/Zend/zend_execute_API.c, line 289.
```
If I remove `$context->join()`, it will instead fail with same assertion error somewhere after the `Loop::run` callback, but before `Loop::run` returns.

Environment:
```
php 7.4.1 zts + parallel
macos
latest amphp/parallel
```

**Comment by autaut03** [comment]
I just tested it with php 7.3.12 (built almost exactly the same as my 7.4.1) and it works good there. 

Should I instead forward this to https://github.com/krakjoe/parallel?

**Comment by kelunik** [comment]
Yup, please.

**Comment by SonarSoftware** [comment]
Setting `opcache.enable_cli=1` works around this.

**Comment by autaut03** [comment]
Closing this in favor of https://github.com/krakjoe/parallel/issues/119. Thanks everyone.

@SonarSoftware I'm getting this on my local machine so turning on Opcache isn't really a solution, sadly.
