### ISSUE TITLE
How to use amphp/parallel to generate PDF files?

### ISSUE THREAD

**Issue by enumag** [amphp/parallel#89]
I'm currently refactoring my application to use `amphp/http-server`. Some of the routes are supposed to generate and return a PDF file to the client. Of course this operation might take a while and I'm not quite sure what the PDF library is doing under the hood so I don't want to do it in the main thread. I'm looking into alternative options like `amphp/parallel`.

What I'm not sure about is how to connect the processes in order to serve the generated PDF to the client. My first thought was that I'd somehow connect the output stream of the child process with the input stream of the `Response` object but I'm not sure how or if it's even possible. Perhaps I'm looking into it in a wrong way?

What I want:
- Avoid having a multi-megabytes PDF file as a string in the memory of the main thread at any given time. (That's why I wanted to connect the streams.)
- Preferably avoid saving the PDF to a disk since I don't really have any need to save it. I just need to generate it and serve it to the client.
- Handle and log potential errors in the child process.

Currently I'm not quite sure what's the best practice for error handling. Should I set up error handling and logging in the child thread? Or should I like `catch (Throwable $e)` and transfer the serialized exceptions to the main thread and take care of logging there?

**Comment by enumag** [comment]
Ideal would be if I could somehow pass the socket where the response socket to the second process to serve the pdf directly.

**Comment by trowski** [comment]
There's a few different ways you could approach this:
1. Start a process/thread that you send data to on stdin and receive the PDF on standard out. If an error occurs, you can send it on stderr. These are streams, so you would not have to buffer anything in memory.
2. Have a child process running a server where you can connect, send the request data, and receive back the PDF. This solution would make it easy to handle the streams, as the first would require some framing to determine when one PDF ended and another began on stdout. You can potentially use `Amp\ByteStream\pipe()` to connect the client socket to the response body.
3. Write a separate process that runs a server (even an HTTP server) that you request PDFs from using an approach similar to (2).

Sending the raw socket to a child process in PHP is… complicated. We have a package `amphp/cluster` where we do it for multiprocess servers, but I wouldn't recommend it for each client (I'm not even sure it's possible).

Of the above solutions, my initial preference is (2). Feel free to ask additional questions here or leave a message in #amphp on [freenode](http://freenode.net) or [AMPHP on Telegram](https://t.me/amphpchat).

**Comment by enumag** [comment]
Thanks!
