### ISSUE TITLE
Add Xdebug forwarding

### ISSUE THREAD

**Issue by Bilge** [amphp/parallel#95]
As remarked in #93, debugging is hard with parallel. I propose that if a debug session is active for the parent process (`xdebug_is_debugger_active() === true`) then the subprocess should be spawned with debugging enabled. At the least, such a facility should be available for opt-in, perhaps enabled by default and perhaps specified at process construction time (to disable).

**Comment by zoltan-patchworks** [comment]
This would be awesome.

**Comment by kelunik** [comment]
This is implemented in 2.x.
